#import "/docs/utils/formulas.typ": building_table, starting_levels
#import "/docs/utils/constants.typ": (
  special_building_construction_duration, special_building_points,
  special_building_population_cost,
)

= 0 C.E. --- Great Library #emph[(Special)] <great-library-special>
#link("#")[← Buildings & Wonders]

== Purpose <purpose>

Knowledge was a strategic resource long before it became a weapon of war. Cities that gathered scholars, philosophers, and engineers gained an advantage not only in culture but in innovation. The Great Library serves as a center of learning where knowledge is collected, debated, and transformed into new discoveries.

Constructing the Great Library strengthens your city's intellectual output and accelerates technological progress.

Once built, the Great Library grants +12 additional research points, which can be invested in technological discoveries. This bonus is added on top of the research generated by your Library and University levels.

Because the Great Library represents the organized body of your city's scholars, it cannot be dismantled while its knowledge is still in use. Before demolishing it, all research points invested through the Great Library must first be refunded to your available research pool.

~ Strategic focus: #strong[Technology] / #strong[long-term advantage]

== Requirements <requirements>

- *Senate* level 21
- *Academy* level 20
- *Harbor* level 5
- Do not have any other special building already built

#figure(
  align(center)[#table(
    columns: 2,
    align: (auto, auto),
    table.header([Property], [Value]),
    table.hline(),
    [#strong[Type];], [Special (non-upgradable)],
    [#strong[Max Level];], [1],
    [#strong[Effects];], [+12 research points for technology research],
  )],
  kind: table,
)

== Starting Levels <starting-levels>
#figure(
  align(center)[#starting_levels(0, 0, 0, 0)],
  kind: table,
)

== Cost <cost>
#let max_level = 1

// ── Base values & Functions ──
#let wood_cost(l) = 7500
#let stone_cost(l) = 9500
#let metal_cost(l) = 7000
#let food_cost(l) = 1000
#let pop_cost(l) = special_building_population_cost
#let total_time(l) = special_building_construction_duration
#let points(l) = special_building_points

#let this_table = (from, to) => building_table(
  from,
  to,
  costs: l => (
    wood_cost(l),
    stone_cost(l),
    metal_cost(l),
    food_cost(l),
    pop_cost(l),
  ),
  time: total_time,
  points: points,
)

#this_table(1, 2)
