#import "/utils/formulas.typ": building_table, starting_levels
#import "/utils/constants.typ": (
  special_building_construction_duration, special_building_points, special_building_population_cost,
)

= 0 C.E. --- Grand Temple #emph[(Special)] <grand-temple-special>
#link("#")[← Buildings & Wonders]

== Purpose <purpose>

Across ancient civilizations, rulers built monumental statues to honor their gods and demonstrate devotion. These great works were not merely symbolic—they were believed to strengthen the bond between the city and the divine powers protecting it.

The Grand Temple stands as a visible offering to the gods, amplifying the religious devotion generated by your temples.

Once constructed, the Grand Temple increases your favor production as if your Shrine or Temple had five additional levels.

For example, a level 10 Shrine will produce favor as if it were level 15 while the Grand Temple stands.

~ Strategic focus: #strong[Religion] / #strong[divine powers]

== Requirements <requirements>

- *Senate* level 21
- *Shrine / Temple* level 12
- *Marketplace* level 5
- Do not have any other special building already built

#figure(
  align(center)[#table(
    columns: 2,
    align: (auto, auto),
    table.header([Property], [Value]),
    table.hline(),
    [#strong[Type];], [Special (non-upgradable)],
    [#strong[Max Level];], [1],
    [#strong[Effects];], [Counts as +5 Shrine / Temple levels for Favor output],
  )],
  kind: table,
)

== Starting Levels <starting-levels>
#figure(
  align(center)[#starting_levels(0, 0, 0, 0)],
  kind: table,
)

== Cost <cost>
#let max_level = 1

// ── Base values & Functions ──
#let wood_cost(l) = 6000
#let stone_cost(l) = 10500
#let metal_cost(l) = 7500
#let food_cost(l) = 5000
#let pop_cost(l) = special_building_population_cost
#let total_time(l) = special_building_construction_duration
#let points(l) = special_building_points

#let this_table = (from, to) => building_table(
  from,
  to,
  costs: l => (
    wood_cost(l),
    stone_cost(l),
    metal_cost(l),
    food_cost(l),
    pop_cost(l),
  ),
  time: total_time,
  points: points,
)

#this_table(1, 2)
